name: Deploy Preview

on:
    push:
        branches:
            - develop

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm ci
            - run: npm run lint
            - run: npm run build

    update-preview:
        needs: test-build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Update preview branch
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git fetch origin

                  git checkout -B preview origin/develop

                  git push origin preview --force
