name: Deploy Preview

on:
    push:
        branches:
            - develop

permissions:
    contents: write

jobs:
    update-preview:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - run: npm ci
            - run: npm run build

            - name: Update preview branch
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git fetch origin

                  git checkout -B preview origin/develop

                  git push origin preview --force
